#
# ~/.bashrc
#cowsay "Hello $USER"
# test
#kitten icat --stdin=no --use-window-size $COLUMNS,$LINES,151,146 --transfer-mode=file ~/.config/neofetch/pngs/doremon.png && neofetch

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
alias grep='grep --color=auto'
PS1='[\u@\h \W]\$ '

neofetch
#pfetch
